Repository codesquad-member-2020/vm-2, pull requests merged in 2020-03, with the labels that each got.

#7 Feature/ui
  client/style/reset.css
  client/style/style.css
  client/view/index.html
  readme.md
Labels: css, html

#15 Feature/render
  client/js/render/render.js
  client/js/wallet/walletMain.js
  client/js/wallet/walletModel.js
  client/js/wallet/walletView.js
  client/view/index.html
  server/vmData.json
Labels: html, js

#16 [Feature/wallet] 지갑 화면 model, view 옵저버 패턴 적용
  .gitignore
  client/js/render/render.js
  client/js/wallet/walletMain.js
  client/js/wallet/walletModel.js
  client/js/wallet/walletView.js
  server/vmData.json
Labels: 리뷰요청

#17 [지갑 화면 구현]
  .gitignore
  client/js/observable.js
  client/js/render/render.js
  client/js/wallet/walletMain.js
  client/js/wallet/walletModel.js
  client/js/wallet/walletView.js
  client/style/reset.css
  client/style/style.css
  client/view/index.html
  server/vmData.json
Labels: 리뷰요청

#19 [상품 선택/메시지창] 상품 선택해 구매하는 기능
  client/js/main.js
  client/js/productList/productListModel.js
  client/js/productList/productListView.js
  client/js/productSelect/productSelectTemplate.js
  client/js/productSelect/productSelectView.js
  client/js/util.js
  client/js/wallet/walletModel.js
  client/js/wallet/walletTemplate.js
  client/js/wallet/walletView.js
Labels: 리뷰요청

#21 [자판기 미션]
  client/js/main.js
  client/js/productList/productListModel.js
  client/js/productList/productListTemplate.js
  client/js/productList/productListView.js
  client/js/productSelect/productSelectTemplate.js
  client/js/productSelect/productSelectView.js
  client/js/render/render.js
  client/js/util.js
  client/js/wallet/walletMain.js
  client/js/wallet/walletModel.js
  client/js/wallet/walletTemplate.js
  client/js/wallet/walletView.js
  client/style/style.css
  client/view/index.html
Labels: 리뷰요청
